name: CitizenCashmere
favicon: null
layout_spectrum: 0.112985780229792
typography_spectrum: 0.07617578841745853
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4100004294887185
  lightness: 0.11186447297222912
  saturation: 0.9879534556530416
  rhythmicContrast: 0.6891603849362582
purpose: []
