name: CitizenCashmere
favicon: null
layout_spectrum: 0.50867
typography_spectrum: 0.50778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#001d70'
    - '#98a8cf'
    - '#414c8f'
    - '#6677a1'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
